# Since we're using workspace, we don't use [packages] nor [dependencies] in this file
[workspace] 

members = [
    "adder",
    "add_one",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

